In [44]:
import pandas as pd
import numpy as np
pd.set_option("display.max_columns", 16)

In [45]:
df = pd.read_csv("ticketsdata\data.csv")

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\tammi\AppData\Local\Temp\ipykernel_52016\248728353.py:1: SyntaxWarning: invalid escape sequence '\d'
  df = pd.read_csv("ticketsdata\data.csv")

In [46]:
df

,subject,body,answer,type,queue,priority,language,version,tag_1,tag_2,tag_3,tag_4,tag_5,tag_6,tag_7,tag_8
0,Wesentlicher Sicherheitsvorfall,"Sehr geehrtes Support-Team,\n\nich möchte eine...",Vielen Dank für die Meldung des kritischen Sic...,Incident,Technical Support,high,de,51,Security,Outage,Disruption,Data Breach,NaN,NaN,NaN,NaN
1,Account Disruption,"Dear Customer Support Team,\n\nI am writing to...","Thank you for reaching out, <name>. We are awa...",Incident,Technical Support,high,en,51,Account,Disruption,Outage,IT,Tech Support,NaN,NaN,NaN
2,Query About Smart Home System Integration Feat...,"Dear Customer Support Team,\n\nI hope this mes...",Thank you for your inquiry. Our products suppo...,Request,Returns and Exchanges,medium,en,51,Product,Feature,Tech Support,NaN,NaN,NaN,NaN,NaN
3,Inquiry Regarding Invoice Details,"Dear Customer Support Team,\n\nI hope this mes...",We appreciate you reaching out with your billi...,Request,Billing and Payments,low,en,51,Billing,Payment,Account,Documentation,Feedback,NaN,NaN,NaN
4,Question About Marketing Agency Software Compa...,"Dear Support Team,\n\nI hope this message reac...",Thank you for your inquiry. Our product suppor...,Problem,Sales and Pre-Sales,medium,en,51,Product,Feature,Feedback,Tech Support,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28582,Performance Problem with Data Analytics Tool,The data analytics tool experiences sluggish p...,We are addressing the performance issue with t...,Incident,Technical Support,high,en,400,Performance,IT,Tech Support,NaN,NaN,NaN,NaN,NaN
28583,Datensperrung in der Kundschaftsbetreuung,"Es gab einen Datensperrungsunfall, bei dem ung...",Ich kann Ihnen bei dem Datensperrungsunfall he...,Incident,Product Support,high,de,400,Security,IT,Tech Support,Bug,NaN,NaN,NaN,NaN
28584,Problem mit der Videokonferenz-Software heute,Wichtigere Sitzungen wurden unterbrochen durch...,"Sehr geehrte/r [Name], leider wurde das Proble...",Incident,Human Resources,low,de,400,Bug,Performance,Network,IT,Tech Support,NaN,NaN,NaN
28585,Update Request for SaaS Platform Integration F...,Requesting an update on the integration featur...,Received your request for updates on the integ...,Change,IT Support,high,en,400,Feature,IT,Tech Support,NaN,NaN,NaN,NaN,NaN
28586,Inquiry About Project Management Features,Looking for detailed information on the projec...,"Dear [Name], thank you for your email regardin...",Request,Technical Support,low,en,400,Feature,Documentation,Feedback,IT,NaN,NaN,NaN,NaN

In [47]:
df.info()
df.shape

<class 'pandas.DataFrame'>
RangeIndex: 28587 entries, 0 to 28586
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   subject   24749 non-null  str
 1   body      28587 non-null  str
 2   answer    28580 non-null  str
 3   type      28587 non-null  str
 4   queue     28587 non-null  str
 5   priority  28587 non-null  str
 6   language  28587 non-null  str
 7   version   28587 non-null  int64
 8   tag_1     28587 non-null  str
 9   tag_2     28574 non-null  str
 10  tag_3     28451 non-null  str
 11  tag_4     25529 non-null  str
 12  tag_5     14545 non-null  str
 13  tag_6     5874 non-null   str
 14  tag_7     2040 non-null   str
 15  tag_8     565 non-null    str
dtypes: int64(1), str(15)
memory usage: 3.5 MB

(28587, 16)

In [48]:
df.isna().sum()

subject      3838
body            0
answer          7
type            0
queue           0
priority        0
language        0
version         0
tag_1           0
tag_2          13
tag_3         136
tag_4        3058
tag_5       14042
tag_6       22713
tag_7       26547
tag_8       28022
dtype: int64

In [49]:
df.columns

Index(['subject', 'body', 'answer', 'type', 'queue', 'priority', 'language',
       'version', 'tag_1', 'tag_2', 'tag_3', 'tag_4', 'tag_5', 'tag_6',
       'tag_7', 'tag_8'],
      dtype='str')

In [50]:
df.drop(columns=[
       'version', 'tag_1', 'tag_2', 'tag_3', 'tag_4', 'tag_5', 'tag_6',
       'tag_7', 'tag_8'],
       inplace=True)
df

,subject,body,answer,type,queue,priority,language
0,Wesentlicher Sicherheitsvorfall,"Sehr geehrtes Support-Team,\n\nich möchte eine...",Vielen Dank für die Meldung des kritischen Sic...,Incident,Technical Support,high,de
1,Account Disruption,"Dear Customer Support Team,\n\nI am writing to...","Thank you for reaching out, <name>. We are awa...",Incident,Technical Support,high,en
2,Query About Smart Home System Integration Feat...,"Dear Customer Support Team,\n\nI hope this mes...",Thank you for your inquiry. Our products suppo...,Request,Returns and Exchanges,medium,en
3,Inquiry Regarding Invoice Details,"Dear Customer Support Team,\n\nI hope this mes...",We appreciate you reaching out with your billi...,Request,Billing and Payments,low,en
4,Question About Marketing Agency Software Compa...,"Dear Support Team,\n\nI hope this message reac...",Thank you for your inquiry. Our product suppor...,Problem,Sales and Pre-Sales,medium,en
...,...,...,...,...,...,...,...
28582,Performance Problem with Data Analytics Tool,The data analytics tool experiences sluggish p...,We are addressing the performance issue with t...,Incident,Technical Support,high,en
28583,Datensperrung in der Kundschaftsbetreuung,"Es gab einen Datensperrungsunfall, bei dem ung...",Ich kann Ihnen bei dem Datensperrungsunfall he...,Incident,Product Support,high,de
28584,Problem mit der Videokonferenz-Software heute,Wichtigere Sitzungen wurden unterbrochen durch...,"Sehr geehrte/r [Name], leider wurde das Proble...",Incident,Human Resources,low,de
28585,Update Request for SaaS Platform Integration F...,Requesting an update on the integration featur...,Received your request for updates on the integ...,Change,IT Support,high,en
28586,Inquiry About Project Management Features,Looking for detailed information on the projec...,"Dear [Name], thank you for your email regardin...",Request,Technical Support,low,en

In [51]:
df = df.loc[df['language'] == 'en',:]
df

,subject,body,answer,type,queue,priority,language
1,Account Disruption,"Dear Customer Support Team,\n\nI am writing to...","Thank you for reaching out, <name>. We are awa...",Incident,Technical Support,high,en
2,Query About Smart Home System Integration Feat...,"Dear Customer Support Team,\n\nI hope this mes...",Thank you for your inquiry. Our products suppo...,Request,Returns and Exchanges,medium,en
3,Inquiry Regarding Invoice Details,"Dear Customer Support Team,\n\nI hope this mes...",We appreciate you reaching out with your billi...,Request,Billing and Payments,low,en
4,Question About Marketing Agency Software Compa...,"Dear Support Team,\n\nI hope this message reac...",Thank you for your inquiry. Our product suppor...,Problem,Sales and Pre-Sales,medium,en
5,Feature Query,"Dear Customer Support,\n\nI hope this message ...",Thank you for your inquiry. Please specify whi...,Request,Technical Support,high,en
...,...,...,...,...,...,...,...
28578,Problem with Billing Adjustment,An unexpected billing discrepancy has been not...,We apologize for the billing discrepancy in th...,Incident,Billing and Payments,high,en
28580,Urgent: Incident Involving Data Breach in Medi...,"A data breach has occurred, which might be rel...","Dear [Name], we acknowledge the urgency of the...",Problem,Product Support,medium,en
28582,Performance Problem with Data Analytics Tool,The data analytics tool experiences sluggish p...,We are addressing the performance issue with t...,Incident,Technical Support,high,en
28585,Update Request for SaaS Platform Integration F...,Requesting an update on the integration featur...,Received your request for updates on the integ...,Change,IT Support,high,en
28586,Inquiry About Project Management Features,Looking for detailed information on the projec...,"Dear [Name], thank you for your email regardin...",Request,Technical Support,low,en

In [52]:
df.isna().sum()

subject     2607
body           0
answer         3
type           0
queue          0
priority       0
language       0
dtype: int64

In [53]:
df.dropna(inplace=True)
df.drop(columns=['answer','language'],inplace=True)

In [54]:
print(df.type.value_counts(),'\n')
print(df.queue.value_counts(),'\n')
print(df.priority.value_counts(),'\n')

type
Incident    5531
Request     3929
Problem     2872
Change      1397
Name: count, dtype: int64

queue
Technical Support                  3971
Product Support                    2606
Customer Service                   2045
IT Support                         1609
Billing and Payments               1349
Returns and Exchanges               686
Service Outages and Maintenance     581
Sales and Pre-Sales                 410
Human Resources                     285
General Inquiry                     187
Name: count, dtype: int64

priority
medium    5593
high      5304
low       2832
Name: count, dtype: int64

In [55]:
df

,subject,body,type,queue,priority
1,Account Disruption,"Dear Customer Support Team,\n\nI am writing to...",Incident,Technical Support,high
2,Query About Smart Home System Integration Feat...,"Dear Customer Support Team,\n\nI hope this mes...",Request,Returns and Exchanges,medium
3,Inquiry Regarding Invoice Details,"Dear Customer Support Team,\n\nI hope this mes...",Request,Billing and Payments,low
4,Question About Marketing Agency Software Compa...,"Dear Support Team,\n\nI hope this message reac...",Problem,Sales and Pre-Sales,medium
5,Feature Query,"Dear Customer Support,\n\nI hope this message ...",Request,Technical Support,high
...,...,...,...,...,...
28578,Problem with Billing Adjustment,An unexpected billing discrepancy has been not...,Incident,Billing and Payments,high
28580,Urgent: Incident Involving Data Breach in Medi...,"A data breach has occurred, which might be rel...",Problem,Product Support,medium
28582,Performance Problem with Data Analytics Tool,The data analytics tool experiences sluggish p...,Incident,Technical Support,high
28585,Update Request for SaaS Platform Integration F...,Requesting an update on the integration featur...,Change,IT Support,high
28586,Inquiry About Project Management Features,Looking for detailed information on the projec...,Request,Technical Support,low

In [56]:
#df.to_json('ticketsdata\clean.json')

In [57]:
df_clean = pd.read_json('ticketsdata\clean.json')
df_clean

<>:1: SyntaxWarning: invalid escape sequence '\c'
<>:1: SyntaxWarning: invalid escape sequence '\c'
C:\Users\tammi\AppData\Local\Temp\ipykernel_52016\798271381.py:1: SyntaxWarning: invalid escape sequence '\c'
  df_clean = pd.read_json('ticketsdata\clean.json')

,subject,body,type,queue,priority
1,Account Disruption,"Dear Customer Support Team,\n\nI am writing to...",Incident,Technical Support,high
2,Query About Smart Home System Integration Feat...,"Dear Customer Support Team,\n\nI hope this mes...",Request,Returns and Exchanges,medium
3,Inquiry Regarding Invoice Details,"Dear Customer Support Team,\n\nI hope this mes...",Request,Billing and Payments,low
4,Question About Marketing Agency Software Compa...,"Dear Support Team,\n\nI hope this message reac...",Problem,Sales and Pre-Sales,medium
5,Feature Query,"Dear Customer Support,\n\nI hope this message ...",Request,Technical Support,high
...,...,...,...,...,...
28578,Problem with Billing Adjustment,An unexpected billing discrepancy has been not...,Incident,Billing and Payments,high
28580,Urgent: Incident Involving Data Breach in Medi...,"A data breach has occurred, which might be rel...",Problem,Product Support,medium
28582,Performance Problem with Data Analytics Tool,The data analytics tool experiences sluggish p...,Incident,Technical Support,high
28585,Update Request for SaaS Platform Integration F...,Requesting an update on the integration featur...,Change,IT Support,high
28586,Inquiry About Project Management Features,Looking for detailed information on the projec...,Request,Technical Support,low